### ISSUE TITLE
Migrate to OCI Artifact from ORAS Artifact

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#652]
Support pushing, attaching and discovering OCI artifacts follow below specs:
https://github.com/opencontainers/distribution-spec/blob/main/spec.md
https://github.com/opencontainers/image-spec/blob/main/artifact.md

# Tasks
## Support OCI Artifact
- [x] https://github.com/oras-project/oras/issues/649
- [x] https://github.com/oras-project/oras/issues/650
- [x] https://github.com/oras-project/oras/issues/651

## Support pushing OCI image as fallback if OCI artifact is not supported
- [x] https://github.com/oras-project/oras/issues/654
- [x] https://github.com/oras-project/oras/issues/658

**Comment by shizhMSFT** [comment]
Closing as all sub-tasks are completed.
