### ISSUE TITLE
add E2E test specs for commands regarding OCI image layout support

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#767]
Currently we have E2E command tests targeting remote registry. After completing https://github.com/oras-project/oras/issues/378, test specs targeting OCI image layout folder/archive files need to be added, including below commands:

- [x] oras blob fetch
- [x] oras blob push
- [x] oras cp: #868
- [x] oras discover: #870
- [x] oras manifest fetch: #863
- [x] oras manifest fetch-config: #864
- [x] oras manifest push: #879 
- [x] oras attach: #881
- [x] oras push: #877
- [x] oras pull: #884
- [x] oras repo tags: #870
